### PR TITLE
add environment prefix to client

### PR DESCRIPTION
**Pull request by estherjsuh**
## Add `environment` prefix to Client
[RED-3025](https://appsembler.atlassian.net/browse/RED-3025)

### CODE REVIEW

**Review by OmarIthawi — CHANGES_REQUESTED** [review]
Thanks @estherjsuh!

Please consider making the `environment` as a `setting` so the Open edX platform don't get affected, otherwise there's a larger cost of development.

```py
class Client:
    def __init__(self, base_url, api_token, environment,
                 read_only_storage=None, cache=None, request_timeout=30):
        """
        Instantiate a new API Client
        """
        self.environment = environment
```

then

```py
    def list_sites(self):
        """
        Returns a list of all Sites
        """
        url = 'v1/environment/{}/site/'.format(self.environment)
        return self.request('get', url)
```

**Comment by estherjsuh** [comment]
@OmarIthawi Thank you for the review! I made the suggested changes, please give this PR another pass

**Review by OmarIthawi — APPROVED** [review]
Looks great! Thanks @estherjsuh.

**Review by thraxil — APPROVED** [review]

**Review by melvinsoft — APPROVED** [review]
🙌

**Pull request merged**
